// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcRazorLabb.Models;

namespace MvcRazorLabb.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220809124351_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcRazorLabb.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Stephen King",
                            IsAvailable = true,
                            Title = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Author = "100miljonersmannen",
                            IsAvailable = true,
                            Title = "Jakten på miljonerna"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jørn Lier Horst",
                            IsAvailable = true,
                            Title = "Gränslöst"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Colleen Hoover",
                            IsAvailable = true,
                            Title = "Ugly Love"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nora Khalil",
                            IsAvailable = true,
                            Title = "Yani"
                        });
                });

            modelBuilder.Entity("MvcRazorLabb.Models.BorrowedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("MvcRazorLabb.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jeremy@jerm.se",
                            FirstName = "Jeremy",
                            LastName = "Cedendahl"
                        },
                        new
                        {
                            Id = 2,
                            Email = "johan@johan.se",
                            FirstName = "Johan",
                            LastName = "Larsson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jandersson@halloj.se",
                            FirstName = "Jesper",
                            LastName = "Andersson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "idaj@yahoo.se",
                            FirstName = "Ida",
                            LastName = "Johansson"
                        },
                        new
                        {
                            Id = 5,
                            Email = "atom@live.se",
                            FirstName = "Anton",
                            LastName = "Johansson"
                        });
                });

            modelBuilder.Entity("MvcRazorLabb.Models.BorrowedBook", b =>
                {
                    b.HasOne("MvcRazorLabb.Models.Book", "Book")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcRazorLabb.Models.Customer", "Customer")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
